name: Check Typos in Source Code

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions repository
        uses: actions/checkout@v4
      - name: Check spelling of repo
        uses: crate-ci/typos@master
        with: 
          files: './src/*','./tests/*','./examples/*'